---
- name: Restart kubelet
  ansible.builtin.service:
    name: kubelet
    state: restarted

- name: Restart AppArmor
  ansible.builtin.service:
    name: apparmor
    enabled: yes
    state: restarted
