---
- hosts: all
  become: yes
  roles:
  - common

- hosts: control
  become: yes
  roles:
  - control

- hosts: node
  become: yes
  roles:
  - node

- hosts: setup
  become: yes
  roles:
  - setup

