---
- name: Install base packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - apparmor-profiles
    - net-tools
    - ipvsadm
    - ipset
    - conntrack
  notify:
  - Stop AppArmor

- name: Install IPVS
  when: "(no_ipvs is undefined) or (no_ipvs|bool == false)"
  block:
  - name: Install ipvs packages
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - ipvsadm
      - ipset
      - conntrack

  - name: Enable ipvs modules
    ansible.builtin.shell: |
      modprobe {{ item }}
    with_items:
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh
    - nf_conntrack

- name: Enable port forwarding
  ansible.builtin.shell: |
    {{ item }}
  with_items:
  - |
    tee /etc/modules-load.d/k8s.conf <<EOF
      overlay
      br_netfilter
    EOF
  - modprobe overlay
  - modprobe br_netfilter
  - |
    tee /etc/sysctl.d/kubernetes.conf<<EOF
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
    EOF
  - sysctl --system

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Update host name resolution
  block:
  - name: Extend hosts file
    ansible.builtin.blockinfile:
      path: /etc/hosts
      marker: "# {mark} {{ item.domain }}"
      block: |
        {{ item.ip }} {{ item.domain }}
    with_items: |
      {{ etc_hosts }}

- name: Get package architecture
  register: dpkg_architecture
  command: dpkg --print-architecture

- name: Install Docker and Containerd
  block:
  - name: Add an apt signing key for Docker
    ansible.builtin.apt_key:
      id: 8D81803C0EBFCD88
      url: https://download.docker.com/linux/ubuntu/gpg
      keyring: /etc/apt/keyrings/docker.gpg

  - name: Add Docker apt source
    ansible.builtin.apt_repository:
      repo: "deb [arch={{ dpkg_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      state: present

  - name: Install Docker and its dependencies
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io 
    notify: Disable Docker daemon
 
  - name: Regenerate Containerd configuration
    ansible.builtin.shell: |
      {{ item }}
    with_items:
    - containerd config default > config.toml
    - sed -i -E 's/(\s+SystemdCgroup\s+=\s+)false/\1true/g' config.toml
    - sudo mv -f config.toml /etc/containerd/
    notify: Restart Containerd 

- name: Install Kubernetes from apt repo
  block:
  - name: Add Kubernetes apt signing key
    ansible.builtin.apt_key:
      id: B53DC80D13EDEF05
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      keyring: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
      state: present

  - name: Add Kubernetes apt source
    ansible.builtin.apt_repository:
      repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
      state: present

  - name: Install Kubernetes binaries
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - kubelet={{ k8s_version + '-00' }}
      - kubeadm={{ k8s_version + '-00' }}
      - kubectl={{ k8s_version + '-00' }}

  - name: Hold installed Kubernetes binaries
    ansible.builtin.dpkg_selections:
      name: "{{ item }}"
      selection: hold
    with_items:
    - kubelet
    - kubeadm
    - kubectl

- name: Install Falco from its apt source
  when: "(no_falco is undefined) or (no_falco|bool == false)"
  block:
  - name: Add Falco apt signing key
    ansible.builtin.apt_key:
      url: https://falco.org/repo/falcosecurity-packages.asc
      state: present

  - name: Add Falco apt source
    ansible.builtin.apt_repository:
      repo: "deb https://download.falco.org/packages/deb stable main"
      state: present

  - name: Remove dialog
    ansible.builtin.apt:
      name: dialog
      state: absent
      update_cache: yes

  - name: Install Falco
    ansible.builtin.apt:
      name: falco
      state: present
      update_cache: yes

- name: Install gVisor
  when: "(no_gvisor is undefined) or (no_gvisor|bool == false)"
  block:
  - name: Add gVisor apt signing key
    ansible.builtin.apt_key:
      url: https://gvisor.dev/archive.key
      keyring: /usr/share/keyrings/gvisor-archive-keyring.gpg
      state: present

  - name: Add gVisor apt source
    ansible.builtin.apt_repository:
      repo: "deb [arch={{ dpkg_architecture.stdout }} signed-by=/usr/share/keyrings/gvisor-archive-keyring.gpg] https://storage.googleapis.com/gvisor/releases release main"
      state: present

  - name: Install gVisor
    ansible.builtin.apt:
      name: runsc
      state: present
      update_cache: yes

