---
- name: Disable Docker daemon
  ansible.builtin.service:
    name: docker
    state: stopped
    enabled: false

- name: Restart Containerd
  ansible.builtin.service:
    name: containerd
    state: restarted

- name: Stop AppArmor
  ansible.builtin.service:
    name: apparmor
    state: stopped
